foreign: spkg_install hacks/wip
- atlas: patch workaround
- cliquer: FIXME: patch build system to set -fno-ivopts accordingly
- cliquer: patches, mkdir
- cliquer: remove testcc.sh call, pulls in too much cruft
- conway_polynomials minor fixes
- conway_polynomials/spkg-install
- cvxopt patch
- flintqs/spkg-install
- gap: patches, do not force gmp location (might be wrong)
- gdmodule
- gfan patch
- iconv: need fix
- lapack/spkg-install
- lcalc: patch workaround
- matplotlib
- maxima patch
- mpfr minor
- mpfr/spkg-install
- mpir: just complain about applied/failing patches, files
- mpir/spkg-install
- ntl: hack
- pari: make gprc.expect accessible
- pari: patch workaround
- pari/spkg-install
- pil complain about patch
- polybori: make custom.py accessible
- polybori: patch workaround
- pygments: just report patch error
- python: allow patches already applied
- python: patch workaround
- ratpoints spkg-install
- readline/spkg-install
- sphinx: just complain about patches
- symmetrica: default values in makefile, patch workaround
- termcap/spkg-install

diff --git a/build/pkgs/ntl/spkg-install b/build/pkgs/ntl/spkg-install
--- a/build/pkgs/ntl/spkg-install
+++ b/build/pkgs/ntl/spkg-install
@@ -46,7 +46,6 @@ ntl_patch()
         patch -p1 < "$patch"
         if [ $? -ne 0 ]; then
             echo >&2 "Error applying '$patch'."
-            exit 1
         fi
     done
 }
@@ -77,8 +76,8 @@ ntl_configure()
     fi
 
     ./configure DEF_PREFIX="$SAGE_LOCAL" SHARED=on \
-        CC="$CC" CFLAGS="$CFLAGS $SHAREDFLAGS" \
-        CXX="$CXX" CXXFLAGS="$CXXFLAGS $SHAREDFLAGS" \
+        CFLAGS="$CFLAGS $SHAREDFLAGS" \
+        CXXFLAGS="$CXXFLAGS $SHAREDFLAGS" \
         LDFLAGS="$LDFLAGS" LIBTOOL_LINK_FLAGS="$LIBTOOL_LINK_FLAGS" \
         NTL_GMP_LIP=on NTL_GF2X_LIB=on NTL_STD_CXX=on \
         LIBTOOL=../libtool/libtool
@@ -112,7 +111,7 @@ ntl_install()
     $MAKE install
 
     if [ $? -ne 0 ]; then
-        echo >&2 "Unable to tune and build NTL."
+        echo >&2 "Unable to install NTL."
         exit 1
     fi
 }
